// app/layout.tsx

import React from 'react'
import './globals.css'
import Navbar from '@/components/Navbar'

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by Next.js'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <Navbar />
        <main>{children}</main>
        <footer >
          <p>&copy; 2024 Product Company. All rights reserved.</p>
        </footer>
      </body>
    </html>
  )
}
